name: Refresh hosts
on:
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # ref https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - run: |
        git config --global user.email spam@krebsco.de
        git config --global user.name krebs
        nix-shell --run generate-hosts
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: refresh hosts
        branch: master
